application: github
version: 1
runtime: python
api_version: 1


handlers:
- url: .*
  script: runner.py
- url: /dataloader/.*
  script: account.py 
  login: admin
- url: /dataloader2/.*
  script: account.py 
  login: admin  
  
  
builtins:
- datastore_admin: on
- remote_api: on

#skip_files: |
# ^bin/.*$|
# ^lib/python2.5/[^/]+$|
# ^(.*/)?(
# (app\.yaml)|
# (app\.yml)|
# (index\.yaml)|
# (index\.yml)|
# (#.*#)|
# (.*~)|
# (.*\.py[co])|
# (.*/RCS/.*)|
# (\..*)|
# )$
